/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClubClubIdIndexRouteImport } from './routes/_authenticated/club.$clubId.index'
import { Route as AuthenticatedClubClubIdDocumentsRouteImport } from './routes/_authenticated/club.$clubId.documents'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClubClubIdIndexRoute =
  AuthenticatedClubClubIdIndexRouteImport.update({
    id: '/club/$clubId/',
    path: '/club/$clubId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClubClubIdDocumentsRoute =
  AuthenticatedClubClubIdDocumentsRouteImport.update({
    id: '/club/$clubId/documents',
    path: '/club/$clubId/documents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/club/$clubId/documents': typeof AuthenticatedClubClubIdDocumentsRoute
  '/club/$clubId/': typeof AuthenticatedClubClubIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/club/$clubId/documents': typeof AuthenticatedClubClubIdDocumentsRoute
  '/club/$clubId': typeof AuthenticatedClubClubIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/club/$clubId/documents': typeof AuthenticatedClubClubIdDocumentsRoute
  '/_authenticated/club/$clubId/': typeof AuthenticatedClubClubIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/club/$clubId/documents'
    | '/club/$clubId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/club/$clubId/documents'
    | '/club/$clubId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/club/$clubId/documents'
    | '/_authenticated/club/$clubId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/club/$clubId/': {
      id: '/_authenticated/club/$clubId/'
      path: '/club/$clubId'
      fullPath: '/club/$clubId/'
      preLoaderRoute: typeof AuthenticatedClubClubIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/club/$clubId/documents': {
      id: '/_authenticated/club/$clubId/documents'
      path: '/club/$clubId/documents'
      fullPath: '/club/$clubId/documents'
      preLoaderRoute: typeof AuthenticatedClubClubIdDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedClubClubIdDocumentsRoute: typeof AuthenticatedClubClubIdDocumentsRoute
  AuthenticatedClubClubIdIndexRoute: typeof AuthenticatedClubClubIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedClubClubIdDocumentsRoute: AuthenticatedClubClubIdDocumentsRoute,
  AuthenticatedClubClubIdIndexRoute: AuthenticatedClubClubIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
